

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_256 = Integer(256); _sage_const_3329 = Integer(3329); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_4 = Integer(4)
n = _sage_const_256 
q = _sage_const_3329 

Z = ZZ['x1']; (x1,) = Z._first_ngens(1)
Zq = GF(q)['x2']; (x2,) = Zq._first_ngens(1)

R = QuotientRing(Z, Z.ideal(x1**n + _sage_const_1 ), names=('y',)); (y,) = R._first_ngens(1)
Rq = QuotientRing(Zq, Zq.ideal(x2**n + _sage_const_1 ), names=('x',)); (x,) = Rq._first_ngens(1)

load("utils.sage")
load("Kyber.sage")

(pk, sk) = CPAPKE_KeyGen(_sage_const_256 , _sage_const_2 , _sage_const_3329 , _sage_const_3 , _sage_const_2 , _sage_const_10 , _sage_const_4 )
print("Public key is: ", pk)
print("Secret key is: ", sk)

